CREATE TABLE analysis_daily_usages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    usage_date DATE NOT NULL,
    request_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_analysis_daily_usages_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT uq_analysis_daily_usages_user_date UNIQUE (user_id, usage_date)
);

CREATE INDEX idx_analysis_daily_usages_user_date
    ON analysis_daily_usages(user_id, usage_date);
